version: "3.9"

services:
  sea-pay-processor:
    build: .
    container_name: sea-pay-processor
    ports:
      - "8092:8080"        # host:container
    environment:
      - SECRET_KEY=change-me
    restart: unless-stopped
